CREATE DATABASE PSIQ
GO

USE PSIQ
GO

CREATE TABLE DIAGNOSTICO
(
	COD		INTEGER PRIMARY KEY IDENTITY(1,1),
	NOME	VARCHAR(1000) NOT NULL
);

CREATE TABLE ESTADO
(
	COD 	INTEGER PRIMARY KEY,
	NOME 	VARCHAR(1000) NOT NULL
);

INSERT INTO ESTADO VALUES (1, 'INSTÁVEL'), (2, 'ESTÁVEL');

CREATE TABLE TERAPEUTA
(
	COD 		  	  INTEGER PRIMARY KEY IDENTITY(1,1),
	CRP 		  	  VARCHAR(50)  NOT NULL,
	SENHA         	  VARCHAR(100) NOT NULL,
	NOME 		  	  VARCHAR(300) NOT NULL,
	EMAIL 		  	  VARCHAR(500) NOT NULL,
	DATA_NASCIMENTO   DATETIME,
	FOTO 		      VARCHAR(1000)
);

INSERT INTO TERAPEUTA (CRP, SENHA, NOME, EMAIL, DATA_NASCIMENTO) VALUES ('12345', '123', 'ADMIN', 'admin@psiq.com.br', GETDATE());

CREATE TABLE PACIENTE
(
	COD 		      INTEGER PRIMARY KEY IDENTITY(1,1),
	CPF 		  	  VARCHAR(50),
	NOME 		      VARCHAR(300) NOT NULL,
	EMAIL 		  	  VARCHAR(500) NOT NULL,
	SENHA         	  VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO   DATETIME,
	FOTO 		      VARCHAR(1000),
	DESCRICAO 	      VARCHAR(MAX),
	COD_TERAPEUTA     INTEGER NOT NULL REFERENCES TERAPEUTA (COD),
	COD_ESTADO	      INTEGER NOT NULL REFERENCES ESTADO (COD)
);

CREATE TABLE PACIENTE_X_DIAGNOSTICO
(
	COD 		    INTEGER PRIMARY KEY IDENTITY(1,1),
	COD_PACIENTE	INTEGER	NOT NULL REFERENCES	PACIENTE (COD),
	COD_DIAGNOSTICO	INTEGER	NOT NULL REFERENCES	DIAGNOSTICO (COD),
	DATA_HORA       DATETIME NOT NULL DEFAULT GETDATE(),
	DESCRICAO	    VARCHAR(MAX)
);

CREATE TABLE POST
(
	COD 		   INTEGER PRIMARY KEY IDENTITY(1,1),
	COD_TERAPEUTA  INTEGER REFERENCES TERAPEUTA (COD),
	COD_PACIENTE   INTEGER REFERENCES PACIENTE (COD),
	DATA_HORA      DATETIME NOT NULL DEFAULT GETDATE(),
	MENSAGEM	   VARCHAR(MAX)
);

select * from DIAGNOSTICO