USE MASTER
GO

CREATE DATABASE PSIQ
GO

USE PSIQ
GO

CREATE TABLE ESTADO
(
	COD 	INTEGER PRIMARY KEY,
	NOME 	VARCHAR(1000) NOT NULL
);

CREATE TABLE TERAPEUTA
(
	COD 		  	  INTEGER PRIMARY KEY IDENTITY(1,1),
	CRP 		  	  VARCHAR(50)  NOT NULL,
	SENHA         	  VARCHAR(100) NOT NULL,
	NOME 		  	  VARCHAR(300) NOT NULL,
	EMAIL 		  	  VARCHAR(500) NOT NULL,
	DATA_NASCIMENTO   DATETIME,
	FOTO 		      VARCHAR(1000),
	CAMINHO_FOTO 	  VARCHAR(3000)
);

CREATE TABLE PACIENTE
(
	COD 		      INTEGER PRIMARY KEY IDENTITY(1,1),
	NOME 		      VARCHAR(300) NOT NULL,
	EMAIL 		  	  VARCHAR(500) NOT NULL,
	SENHA         	  VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO   DATETIME,
	FOTO 		      VARCHAR(1000),
	CAMINHO_FOTO 	  VARCHAR(3000),
	DESCRICAO 	      VARCHAR(MAX),
	COD_TERAPEUTA     INTEGER NOT NULL REFERENCES TERAPEUTA (COD),
	COD_ESTADO	      INTEGER REFERENCES ESTADO (COD)
);

CREATE TABLE DIAGNOSTICO
(
	COD		INTEGER PRIMARY KEY IDENTITY(1,1),
	NOME	VARCHAR(1000) NOT NULL
);

CREATE TABLE PACIENTE_X_DIAGNOSTICO
(
	COD_PACIENTE	INTEGER	NOT NULL REFERENCES	PACIENTE,
	COD_DIAGNOSTICO	INTEGER	NOT NULL REFERENCES	DIAGNOSTICO,
	CONSTRAINT PK_PACIENTE_X_DIAGNOSTICO PRIMARY KEY (COD_PACIENTE, COD_DIAGNOSTICO)
);

CREATE TABLE POST
(
	COD 		   INTEGER PRIMARY KEY IDENTITY(1,1),
	COD_TERAPEUTA  INTEGER NOT NULL REFERENCES TERAPEUTA,
	COD_PACIENTE   INTEGER NOT NULL REFERENCES PACIENTE,
	DATA_HORA      DATETIME NOT NULL DEFAULT GETDATE(),
	MENSAGEM VARCHAR(MAX)
);